---
version: "2"
services:
    www:
        build: .
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:8.3.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: huy
            MYSQL_PASSWORD: huy
            MYSQL_ROOT_PASSWORD: huy
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 82:80
        environment:
            MYSQL_USER: huy
            MYSQL_PASSWORD: huy
            MYSQL_ROOT_PASSWORD: huy
volumes:
    persistent:
